### mk-define-groups ###
# mkfile script with dependency rules for:
# 1. Count samples per group.
# 2. Join in a file samples per group.
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.PREPARE_GROUPS:QV: %.sample_count.tmp
	echo "[DEBUG] preparing samples, with at least $NUMBER_OF_SAMPLES_CUTOFF samples"
	for group in $( awk -v cutoff="$NUMBER_OF_SAMPLES_CUTOFF" '$1 >= cutoff {print $2}' $prereq )
	do
		ofile="$(dirname $stem)/group_$group.tsv"
		echo "output file is $ofile"
		awk -v ethnic="$group" '$2 == ethnic {print $1}' $stem.tsv \
		| tr "\n" "," | sed "s#,\$##" > $ofile
	done \
	&& rm $prereq

%.sample_count.tmp:Q: %.tsv
	echo "[DEBUG] count samples per group"
	tail -n+2 $prereq \
	| cut -f2 | sort | uniq -c \
	| tr -s " " | sed "s# ##" | sort -nr > $target
