### mk-select-world-rare ###
# mkfile script with dependency rules for:
# 1. Count samples per group.
# 2. Join in a file samples per group.
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.world_rare.vcf:Q: %.vcf.gz
	## Filter vep is a VEP tool described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html
	# -i, input file
	# -o, output file
	# --vcf_info_field, VEP finds annotations in ANN field
	# -filter, VEP finds selection signals.
	# --force_overwrite, forces an ouput file
	echo "[DEBUG] selecting singletons"
	filter_vep \
		-i $prereq \
		-o $target \
		--vcf_info_field ANN \
		-filter "(MAX_AF < 0.005 and gnomADg_AF < 0.005) or (MAX_AF < 0.005 and not gnomADg_AF) or (not MAX_AF and gnomADg_AF < 0.005) or (not MAX_AF and not gnomADg_AF)" \
		--force_overwrite
