### mk-count-and-plot ###
# mkfile script with dependency rules for:
# 1. To count number of discernible variants per group and type in a tsv file.
# 2. To plot number of discernible variants per group and type.
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html
MKSHELL=/bin/bash

private_variants_per_group.pdf:Q: private_variants_per_group.tsv
	# This block of code uses plotter.R to format results.
	echo "[DEBUG] plotting data"
	Rscript --vanilla plotter.R

private_variants_per_group.tsv:Q:
	echo "[DEBUG] counting and gathering variant counts"
	echo "group variant_type number" | tr " " "\t" > $target
	for vcffile in $(find -L . -name "group_*.vcf")
	do
		echo "[>..] counting $vcffile"
		## For more information about 'bcftools' commands, see https://samtools.github.io/bcftools/bcftools.html
		## view --types indels/snps to keep the specific type of variant.
		group=$(basename $vcffile .vcf | sed "s#group_##")
		variant_type="snv"
		numbers=$(bcftools view -H --types snps $vcffile | wc -l)
		echo "$group $variant_type $numbers" | tr " " "\t" >> $target
		variant_type="indel"
		numbers=$(bcftools view -H --types indels $vcffile | wc -l)
		echo "$group $variant_type $numbers" | tr " " "\t" >> $target
	done
